package com.example.ems.asset.entity;

public enum AssetEventType {
    ASSET_CREATED,
    ASSET_UPDATED,
    ASSET_DELETED,
    CATEGORY_CHANGED,
    LOCATION_CHANGED,
    ASSIGNED,
    TRANSFERRED,
    RETURNED,
    STATUS_CHANGED,
    MAINTENANCE_CREATED,
    MAINTENANCE_STARTED,
    MAINTENANCE_COMPLETED,
    MAINTENANCE_CANCELLED,
    RETIRED,
    DISPOSED
}
