package com.example.ems.common.entity;

public enum NotificationType {
    // Approval
    APPROVAL_ACTION_REQUIRED,
    APPROVAL_SUBMITTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    APPROVAL_CANCELLED,
    APPROVAL_ESCALATED,

    // Assignment
    ASSIGNMENT_CREATED,
    ASSIGNMENT_ACCEPTED,
    ASSIGNMENT_REJECTED,
    ASSIGNMENT_REASSIGNED,
    ASSIGNMENT_OVERDUE,

    // Employee
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_OFFBOARDED,

    // Leave
    LEAVE_SUBMITTED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,

    // Attendance
    ATTENDANCE_MISSED,
    ATTENDANCE_REGULARIZATION_REQUIRED,

    // Payroll
    PAYROLL_PROCESSED,
    PAYROLL_FAILED,

    // Support
    TICKET_ASSIGNED,
    TICKET_UPDATED,
    TICKET_ESCALATED,

    // System
    SYSTEM_ALERT,
    SYSTEM_ANNOUNCEMENT
}
