apiVersion: v1
kind: Secret
metadata:
  name: ems-secret
  namespace: ems
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: "MTIzNDU=" # base64 of 12345
  RAZORPAY_KEY_SECRET: "dXF5eXE2OEc2RHlkajNGSlhnb2JEZUIw" # base64 of uq9yq68G6Dydj3FJXgobDeB0
