-- Flyway Migration: V105__evolve_notifications_and_create_delivery_tables.sql
-- Evolution of notifications schema for multi-tenant, event-driven, and permission-aware architecture

-- 1. Extend notifications table with multi-tenant, category, entity, and action tracking
ALTER TABLE public.notifications
    ADD COLUMN IF NOT EXISTS organization_id bigint,
    ADD COLUMN IF NOT EXISTS category character varying(50) DEFAULT 'SYSTEM' NOT NULL,
    ADD COLUMN IF NOT EXISTS action_required boolean DEFAULT false NOT NULL,
    ADD COLUMN IF NOT EXISTS entity_type character varying(100),
    ADD COLUMN IF NOT EXISTS entity_id bigint,
    ADD COLUMN IF NOT EXISTS metadata text,
    ADD COLUMN IF NOT EXISTS read_at timestamp(6) without time zone,
    ADD COLUMN IF NOT EXISTS dismissed boolean DEFAULT false NOT NULL,
    ADD COLUMN IF NOT EXISTS dismissed_at timestamp(6) without time zone,
    ADD COLUMN IF NOT EXISTS expires_at timestamp(6) without time zone;

-- 2. Backfill organization_id from users table where available
UPDATE public.notifications n
SET organization_id = u.organization_id
FROM public.users u
WHERE n.user_id = u.id AND n.organization_id IS NULL;

-- 3. Add foreign key from notifications to organizations if organizations exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_notifications_organization'
    ) THEN
        ALTER TABLE public.notifications
            ADD CONSTRAINT fk_notifications_organization
            FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE;
    END IF;
END $$;

-- 4. Create performance & lookup indexes on notifications
CREATE INDEX IF NOT EXISTS idx_notifications_user_org_read 
    ON public.notifications (user_id, organization_id, is_read);

CREATE INDEX IF NOT EXISTS idx_notifications_org_id 
    ON public.notifications (organization_id);

CREATE INDEX IF NOT EXISTS idx_notifications_category 
    ON public.notifications (category);

CREATE INDEX IF NOT EXISTS idx_notifications_entity 
    ON public.notifications (entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_notifications_dismissed 
    ON public.notifications (dismissed);

-- 5. Create notification_deliveries table for multi-channel dispatch tracking
CREATE TABLE IF NOT EXISTS public.notification_deliveries (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.notification_deliveries_id_seq),
    notification_id bigint NOT NULL,
    recipient_user_id bigint NOT NULL,
    channel character varying(50) NOT NULL,
    status character varying(50) NOT NULL DEFAULT 'PENDING',
    sent_at timestamp(6) without time zone,
    failed_at timestamp(6) without time zone,
    failure_reason character varying(500),
    attempt_count integer NOT NULL DEFAULT 0,
    created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notification_deliveries_pkey PRIMARY KEY (id),
    CONSTRAINT fk_notification_deliveries_notification FOREIGN KEY (notification_id) REFERENCES public.notifications(id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_deliveries_recipient FOREIGN KEY (recipient_user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_notification_deliveries_notification 
    ON public.notification_deliveries (notification_id);

CREATE INDEX IF NOT EXISTS idx_notification_deliveries_recipient 
    ON public.notification_deliveries (recipient_user_id);

CREATE INDEX IF NOT EXISTS idx_notification_deliveries_channel_status 
    ON public.notification_deliveries (channel, status);
