CREATE TABLE public.reminders (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.reminders_id_seq),
    title character varying(255) NOT NULL,
    description text,
    reminder_date timestamp(6) without time zone NOT NULL,
    employee_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT reminders_pkey PRIMARY KEY (id),
    CONSTRAINT fk_reminders_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE
);
