CREATE TABLE public.organizations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.organizations_id_seq),
    organization_code character varying(255) NOT NULL UNIQUE,
    name character varying(255) NOT NULL,
    email character varying(255),
    phone character varying(255),
    website character varying(255),
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT organizations_pkey PRIMARY KEY (id)
);

CREATE TABLE public.organization_addresses (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.organization_addresses_id_seq),
    organization_id bigint NOT NULL,
    street character varying(255),
    city character varying(255),
    state character varying(255),
    country character varying(255),
    zip_code character varying(255),
    CONSTRAINT organization_addresses_pkey PRIMARY KEY (id),
    CONSTRAINT fk_organization_address_org FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);

CREATE TABLE public.organization_settings (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.organization_settings_id_seq),
    organization_id bigint NOT NULL,
    config jsonb,
    CONSTRAINT organization_settings_pkey PRIMARY KEY (id),
    CONSTRAINT fk_organization_settings_org FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);

CREATE TABLE public.subscriptions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.subscriptions_id_seq),
    organization_id bigint NOT NULL,
    plan_code character varying(255) NOT NULL,
    plan_name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    start_date date NOT NULL,
    expiry_date date NOT NULL,
    auto_renew boolean DEFAULT false NOT NULL,
    billing_info jsonb,
    limits_info jsonb,
    features_info jsonb,
    payment_info jsonb,
    notes text,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT fk_subscriptions_org FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);

CREATE TABLE public.subscription_invoices (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.subscription_invoices_id_seq),
    subscription_id bigint NOT NULL,
    invoice_number character varying(255) NOT NULL UNIQUE,
    amount numeric(38,2) NOT NULL,
    currency character varying(10) NOT NULL,
    tax numeric(38,2),
    discount numeric(38,2),
    status character varying(50) NOT NULL,
    issued_at timestamp(6) without time zone NOT NULL,
    due_at date,
    paid_at timestamp(6) without time zone,
    pdf_content bytea,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT subscription_invoices_pkey PRIMARY KEY (id),
    CONSTRAINT fk_subscription_invoices_sub FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id) ON DELETE CASCADE
);

CREATE TABLE public.subscription_history (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.subscription_history_id_seq),
    subscription_id bigint NOT NULL,
    action character varying(255) NOT NULL,
    old_plan character varying(255),
    new_plan character varying(255),
    old_status character varying(255),
    new_status character varying(255),
    performed_by character varying(255) NOT NULL,
    performed_at timestamp(6) without time zone NOT NULL,
    remarks text,
    CONSTRAINT subscription_history_pkey PRIMARY KEY (id)
);

CREATE TABLE public.organization_audit_logs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.organization_audit_logs_id_seq),
    organization_id bigint NOT NULL,
    action character varying(255) NOT NULL,
    entity character varying(255),
    entity_id bigint,
    performed_by character varying(255) NOT NULL,
    performed_at timestamp(6) without time zone NOT NULL,
    ip_address character varying(255),
    user_agent character varying(255),
    old_values jsonb,
    new_values jsonb,
    CONSTRAINT organization_audit_logs_pkey PRIMARY KEY (id),
    CONSTRAINT fk_organization_audit_logs_org FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);

ALTER TABLE public.users ADD COLUMN organization_id bigint;
ALTER TABLE public.employees ADD COLUMN organization_id bigint;
ALTER TABLE public.departments ADD COLUMN organization_id bigint;

ALTER TABLE public.users ADD CONSTRAINT fk_users_org FOREIGN KEY (organization_id) REFERENCES public.organizations(id);
ALTER TABLE public.employees ADD CONSTRAINT fk_employees_org FOREIGN KEY (organization_id) REFERENCES public.organizations(id);
ALTER TABLE public.departments ADD CONSTRAINT fk_departments_org FOREIGN KEY (organization_id) REFERENCES public.organizations(id);

CREATE INDEX idx_org_name ON public.organizations(name);
CREATE INDEX idx_org_code ON public.organizations(organization_code);
CREATE INDEX idx_employee_org ON public.employees(organization_id);
CREATE INDEX idx_department_org ON public.departments(organization_id);
CREATE INDEX idx_user_org ON public.users(organization_id);
CREATE INDEX idx_subscription_org ON public.subscriptions(organization_id);
CREATE INDEX idx_subscription_status ON public.subscriptions(status);
CREATE INDEX idx_audit_org ON public.organization_audit_logs(organization_id);
