CREATE TABLE public.payments (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.payments_id_seq),
    invoice_id bigint NOT NULL,
    gateway character varying(255) NOT NULL,
    gateway_order_id character varying(255),
    gateway_payment_id character varying(255) UNIQUE,
    gateway_refund_id character varying(255),
    amount numeric(38,2) NOT NULL,
    currency character varying(10) NOT NULL,
    payment_method character varying(50),
    status character varying(50) NOT NULL,
    receipt character varying(255),
    paid_at timestamp(6) without time zone,
    refund_amount numeric(38,2),
    refund_reason character varying(255),
    refunded_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id) REFERENCES public.subscription_invoices(id) ON DELETE CASCADE
);

CREATE INDEX idx_payments_invoice ON public.payments(invoice_id);
CREATE INDEX idx_payments_gateway_order ON public.payments(gateway_order_id);
