CREATE TABLE public.processed_events (
    event_key character varying(255) NOT NULL,
    processed_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT processed_events_pkey PRIMARY KEY (event_key)
);

CREATE TABLE public.event_retry_queue (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_id character varying(255) NOT NULL,
    event_type character varying(100) NOT NULL,
    handler_name character varying(100) NOT NULL,
    payload text NOT NULL,
    retry_count integer NOT NULL DEFAULT 0,
    max_retries integer NOT NULL DEFAULT 3,
    status character varying(50) NOT NULL,
    last_error text,
    dead_letter_reason text,
    dead_letter_timestamp timestamp(6) without time zone,
    next_retry_at timestamp(6) without time zone NOT NULL,
    last_attempt_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT event_retry_queue_pkey PRIMARY KEY (id)
);

CREATE TABLE public.event_execution_log (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_id character varying(255) NOT NULL,
    handler_name character varying(100) NOT NULL,
    status character varying(50) NOT NULL,
    error_message text,
    duration_ms bigint,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT event_execution_log_pkey PRIMARY KEY (id)
);
