-- Migrate any legacy FAILED idempotency states to FAILED_TRANSIENT
UPDATE public.idempotency_keys SET status = 'FAILED_TRANSIENT' WHERE status = 'FAILED';

-- Check Constraint for subscription status
ALTER TABLE public.subscriptions 
ADD CONSTRAINT valid_subscription_status 
CHECK (status IN ('TRIAL', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'SUSPENDED', 'PENDING', 'ARCHIVED', 'INCOMPLETE', 'PENDING_PAYMENT', 'PAST_DUE'));

-- Check Constraint for invoice status
ALTER TABLE public.subscription_invoices 
ADD CONSTRAINT valid_invoice_status 
CHECK (status IN ('DRAFT', 'ISSUED', 'PAID', 'VOID', 'OVERDUE'));

-- Check Constraint for idempotency keys
ALTER TABLE public.idempotency_keys
ADD CONSTRAINT valid_idempotency_status
CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED_TRANSIENT', 'FAILED_PERMANENT'));

-- Create invoice_state_log table
CREATE TABLE public.invoice_state_log (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    invoice_id bigint NOT NULL,
    from_state character varying(50),
    to_state character varying(50) NOT NULL,
    performed_by character varying(100) NOT NULL,
    remarks text,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT invoice_state_log_pkey PRIMARY KEY (id)
);
