DROP TABLE IF EXISTS public.analytics_payment_facts CASCADE;
DROP TABLE IF EXISTS public.analytics_event_log CASCADE;
DROP TABLE IF EXISTS public.analytics_snapshot_run CASCADE;

-- 1. Immutable Event Ledger
CREATE TABLE public.analytics_event_log (
    event_global_sequence bigserial NOT NULL,
    event_id character varying(255) NOT NULL,
    subscription_id bigint NOT NULL,
    event_type character varying(100) NOT NULL,
    event_payload jsonb NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT analytics_event_log_pkey PRIMARY KEY (event_global_sequence),
    CONSTRAINT analytics_event_log_event_id_key UNIQUE (event_id)
);

-- 2. Normalized Analytics Facts Table (no performance-reducing foreign key constraint)
CREATE TABLE public.analytics_payment_facts (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_global_sequence bigint NOT NULL,
    subscription_id bigint NOT NULL,
    amount numeric(20, 2) NOT NULL DEFAULT 0.00,
    status character varying(50) NOT NULL,
    plan_code character varying(50) NOT NULL,
    billing_cycle character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT analytics_payment_facts_pkey PRIMARY KEY (id)
);

-- 3. Snapshot Run tracking
CREATE TABLE public.analytics_snapshot_run (
    rebuild_id character varying(100) NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    completed_at timestamp(6) without time zone,
    mode character varying(50) NOT NULL,
    status character varying(50) NOT NULL,
    rebuild_end_sequence bigint NOT NULL DEFAULT 0,
    estimated_duration_ms bigint NOT NULL DEFAULT 0,
    projection_version bigint NOT NULL DEFAULT 0,
    CONSTRAINT analytics_snapshot_run_pkey PRIMARY KEY (rebuild_id)
);

CREATE INDEX IF NOT EXISTS idx_payment_facts_seq ON public.analytics_payment_facts(event_global_sequence);
CREATE INDEX IF NOT EXISTS idx_metrics_date ON public.subscription_metrics_daily(date);
CREATE INDEX IF NOT EXISTS idx_plan_summary_plan ON public.subscription_plan_summary(plan_code);
