DROP TABLE IF EXISTS public.analytics_payment_facts;
DROP TABLE IF EXISTS public.analytics_event_log CASCADE;
DROP TABLE IF EXISTS public.analytics_snapshot_run;

-- 1. Immutable Event Ledger
CREATE TABLE public.analytics_event_log (
    event_global_sequence bigserial NOT NULL,
    event_id character varying(255) NOT NULL,
    subscription_id bigint NOT NULL,
    event_type character varying(100) NOT NULL,
    event_payload jsonb NOT NULL,
    created_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT analytics_event_log_pkey PRIMARY KEY (event_global_sequence),
    CONSTRAINT analytics_event_log_event_id_key UNIQUE (event_id)
);

-- 2. Normalized Analytics Facts Table
CREATE TABLE public.analytics_payment_facts (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_global_sequence bigint NOT NULL,
    subscription_id bigint NOT NULL,
    amount numeric(20, 2) NOT NULL DEFAULT 0.00,
    status character varying(50) NOT NULL,
    plan_code character varying(50) NOT NULL,
    billing_cycle character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT analytics_payment_facts_pkey PRIMARY KEY (id),
    CONSTRAINT uq_facts_event UNIQUE (event_global_sequence)
);

-- 3. Snapshot Run tracking
CREATE TABLE public.analytics_snapshot_run (
    rebuild_id character varying(100) NOT NULL,
    started_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    completed_at timestamp(6) without time zone,
    mode character varying(50) NOT NULL,
    status character varying(50) NOT NULL,
    rebuild_end_sequence bigint NOT NULL DEFAULT 0,
    estimated_duration_ms bigint NOT NULL DEFAULT 0,
    projection_version bigint NOT NULL DEFAULT 0,
    CONSTRAINT analytics_snapshot_run_pkey PRIMARY KEY (rebuild_id)
);

-- Partial unique index to enforce exactly one active running rebuild job (concurrency guard)
CREATE UNIQUE INDEX idx_one_running_rebuild ON public.analytics_snapshot_run (status) WHERE status = 'RUNNING';

CREATE INDEX idx_payment_facts_seq ON public.analytics_payment_facts(event_global_sequence);
