-- V23: Support Module Platform Admin Tables and Enhancements

-- 1. Alter my_support_comments to add is_internal
ALTER TABLE public.my_support_comments ADD COLUMN is_internal boolean DEFAULT false NOT NULL;

-- 2. Alter my_support_timeline_activities to add action, old_value, new_value
ALTER TABLE public.my_support_timeline_activities ADD COLUMN action character varying(50);
ALTER TABLE public.my_support_timeline_activities ADD COLUMN old_value character varying(255);
ALTER TABLE public.my_support_timeline_activities ADD COLUMN new_value character varying(255);

-- 3. Alter my_support_tickets to add organization_id, soft delete, and merge fields
ALTER TABLE public.my_support_tickets ADD COLUMN organization_id bigint;
ALTER TABLE public.my_support_tickets ADD COLUMN merged_into_ticket_id bigint;
ALTER TABLE public.my_support_tickets ADD COLUMN merged_by character varying(255);
ALTER TABLE public.my_support_tickets ADD COLUMN merged_at timestamp(6) without time zone;
ALTER TABLE public.my_support_tickets ADD COLUMN merge_reason text;
ALTER TABLE public.my_support_tickets ADD COLUMN is_deleted boolean DEFAULT false NOT NULL;
ALTER TABLE public.my_support_tickets ADD COLUMN deleted_at timestamp(6) without time zone;
ALTER TABLE public.my_support_tickets ADD COLUMN deleted_by character varying(255);

-- Add foreign key constraints
ALTER TABLE public.my_support_tickets ADD CONSTRAINT fk_my_support_tickets_org FOREIGN KEY (organization_id) REFERENCES public.organizations(id);
ALTER TABLE public.my_support_tickets ADD CONSTRAINT fk_my_support_tickets_merged FOREIGN KEY (merged_into_ticket_id) REFERENCES public.my_support_tickets(id);

-- 4. Create support_sla table
CREATE TABLE public.support_sla (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.support_sla_id_seq),
    priority character varying(50) NOT NULL UNIQUE,
    response_time_minutes integer NOT NULL,
    resolution_time_minutes integer NOT NULL,
    business_hours_only boolean DEFAULT false NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    escalation_after_minutes integer,
    auto_close_after_days integer,
    warning_before_minutes integer,
    CONSTRAINT support_sla_pkey PRIMARY KEY (id)
);

-- 5. Create support_templates table
CREATE TABLE public.support_templates (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.support_templates_id_seq),
    title character varying(255) NOT NULL,
    content text NOT NULL,
    category character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT support_templates_pkey PRIMARY KEY (id)
);

-- 6. Create support_notifications table
CREATE TABLE public.support_notifications (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.support_notifications_id_seq),
    type character varying(50) NOT NULL,
    receiver_user_id bigint,
    sender_user_id bigint,
    ticket_id bigint,
    link character varying(255),
    is_read boolean DEFAULT false NOT NULL,
    read_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT support_notifications_pkey PRIMARY KEY (id),
    CONSTRAINT fk_support_notifications_receiver FOREIGN KEY (receiver_user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_support_notifications_sender FOREIGN KEY (sender_user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_support_notifications_ticket FOREIGN KEY (ticket_id) REFERENCES public.my_support_tickets(id) ON DELETE CASCADE
);

-- 7. Create support_ticket_assignments table
CREATE TABLE public.support_ticket_assignments (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.support_ticket_assignments_id_seq),
    ticket_id bigint NOT NULL,
    assigned_to character varying(255) NOT NULL,
    assigned_by character varying(255) NOT NULL,
    assigned_at timestamp(6) without time zone NOT NULL,
    unassigned_at timestamp(6) without time zone,
    reason character varying(255),
    assignment_type character varying(50) DEFAULT 'MANUAL' NOT NULL,
    CONSTRAINT support_ticket_assignments_pkey PRIMARY KEY (id),
    CONSTRAINT fk_support_ticket_assignments_ticket FOREIGN KEY (ticket_id) REFERENCES public.my_support_tickets(id) ON DELETE CASCADE
);

-- Indexing for lookup performance
CREATE INDEX idx_support_ticket_org ON public.my_support_tickets(organization_id);
CREATE INDEX idx_support_ticket_deleted ON public.my_support_tickets(is_deleted);
CREATE INDEX idx_support_notifications_receiver ON public.support_notifications(receiver_user_id);
CREATE INDEX idx_support_ticket_assignments_ticket ON public.support_ticket_assignments(ticket_id);
