ALTER TABLE my_support_categories
ADD COLUMN description VARCHAR(255),
ADD COLUMN color VARCHAR(50),
ADD COLUMN status VARCHAR(20) DEFAULT 'ACTIVE',
ADD COLUMN display_order INT DEFAULT 0,
ADD COLUMN is_default BOOLEAN DEFAULT FALSE,
ADD COLUMN is_system BOOLEAN DEFAULT FALSE,
ADD COLUMN created_by VARCHAR(100),
ADD COLUMN updated_by VARCHAR(100),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_at TIMESTAMP;
