-- V29: Create Report Export History table

CREATE TABLE IF NOT EXISTS report_export_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_name    VARCHAR(255) NOT NULL,
    report_type    VARCHAR(100) NOT NULL,
    export_format  VARCHAR(50)  NOT NULL,
    created_by     VARCHAR(255) NOT NULL,
    organization_id BIGINT,
    status         VARCHAR(50)  NOT NULL DEFAULT 'PENDING',
    download_url   VARCHAR(1000),
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexing for quick lookups on exports
CREATE INDEX idx_report_export_history_created_by ON report_export_history(created_by);
CREATE INDEX idx_report_export_history_status ON report_export_history(status);
