-- Create tenants table
CREATE TABLE public.tenants (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    subdomain character varying(255) NOT NULL,
    timezone character varying(100) NOT NULL,
    currency character varying(10) NOT NULL,
    locale character varying(10) NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT tenants_pkey PRIMARY KEY (id),
    CONSTRAINT fk_tenants_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX idx_tenants_subdomain ON public.tenants(subdomain);

-- Create email_verifications table
CREATE TABLE public.email_verifications (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    verified_at timestamp without time zone,
    attempts integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT email_verifications_pkey PRIMARY KEY (id),
    CONSTRAINT fk_email_verifications_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX idx_email_verifications_token ON public.email_verifications(token);

-- Alter organizations table to add core fields
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS industry character varying(255);
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS gst_number character varying(255);
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS reg_number character varying(255);
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS status character varying(50);
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS normalized_name character varying(255);

CREATE UNIQUE INDEX idx_orgs_normalized_name ON public.organizations(normalized_name);

-- Alter subscriptions table to add trial and limit details
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS trial boolean DEFAULT false NOT NULL;
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS trial_end date;
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS employee_limit integer NOT NULL DEFAULT 25;

-- Alter users table to add OAuth support fields and make password nullable
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS provider character varying(50) DEFAULT 'LOCAL' NOT NULL;
ALTER TABLE public.users ALTER COLUMN password DROP NOT NULL;
