ALTER TABLE employees ADD COLUMN first_name VARCHAR(255);
ALTER TABLE employees ADD COLUMN last_name VARCHAR(255);
ALTER TABLE employees ADD COLUMN personal_mobile VARCHAR(255);
ALTER TABLE employees ADD COLUMN work_mobile VARCHAR(255);
ALTER TABLE employees ADD COLUMN current_address VARCHAR(255);
ALTER TABLE employees ADD COLUMN permanent_address VARCHAR(255);
ALTER TABLE employees ADD COLUMN same_address BOOLEAN DEFAULT FALSE;
ALTER TABLE employees ADD COLUMN emergency_contact_name VARCHAR(255);
ALTER TABLE employees ADD COLUMN emergency_contact_number VARCHAR(255);
ALTER TABLE employees ADD COLUMN marital_status VARCHAR(255);
ALTER TABLE employees ADD COLUMN blood_group VARCHAR(255);
ALTER TABLE employees ADD COLUMN nationality VARCHAR(255);
ALTER TABLE employees ADD COLUMN aadhaar_number VARCHAR(255);
ALTER TABLE employees ADD COLUMN pan_number VARCHAR(255);
ALTER TABLE employees ADD COLUMN uan_number VARCHAR(255);
ALTER TABLE employees ADD COLUMN passport_number VARCHAR(255);
ALTER TABLE employees ADD COLUMN source_of_hire VARCHAR(255);
ALTER TABLE employees ADD COLUMN total_experience VARCHAR(255);
ALTER TABLE employees ADD COLUMN notes TEXT;
ALTER TABLE employees ADD COLUMN probation_end_date DATE;
ALTER TABLE employees ADD COLUMN send_invite BOOLEAN DEFAULT TRUE;
ALTER TABLE employees ADD COLUMN notify_manager BOOLEAN DEFAULT TRUE;
ALTER TABLE employees ADD COLUMN notify_hr BOOLEAN DEFAULT FALSE;
ALTER TABLE employees ADD COLUMN reminder_unopened BOOLEAN DEFAULT TRUE;
