-- Create company_settings table conditionally if it does not already exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'company_settings') THEN
        CREATE TABLE public.company_settings (
            id bigint NOT NULL,
            address character varying(255),
            company_name character varying(255),
            fiscal_year_start character varying(255),
            logo_url character varying(255),
            phone character varying(255),
            registration_number character varying(255),
            tax_id character varying(255),
            website character varying(255),
            CONSTRAINT company_settings_pkey PRIMARY KEY (id)
        );

        -- Add generated identity behavior for id column
        ALTER TABLE public.company_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.company_settings_id_seq
        );
    END IF;
END
$$;
