-- Create otp_tokens table conditionally if it does not already exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'otp_tokens') THEN
        CREATE TABLE public.otp_tokens (
            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            email character varying(255) NOT NULL,
            otp_hash character varying(255),
            attempt_count integer NOT NULL DEFAULT 0,
            created_at timestamp without time zone NOT NULL,
            expiry_time timestamp without time zone NOT NULL,
            reset_token character varying(255),
            CONSTRAINT otp_tokens_pkey PRIMARY KEY (id)
        );
        CREATE UNIQUE INDEX idx_otp_tokens_email ON public.otp_tokens(email);
        CREATE INDEX idx_otp_tokens_reset_token ON public.otp_tokens(reset_token);
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'user_sessions') THEN
        CREATE TABLE public.user_sessions (
            session_id character varying(255) NOT NULL,
            user_id character varying(255) NOT NULL,
            email character varying(255) NOT NULL,
            user_agent character varying(1024),
            ip_address character varying(255),
            refresh_token character varying(255) NOT NULL,
            created_at timestamp without time zone NOT NULL,
            expiry_time timestamp without time zone NOT NULL,
            is_revoked boolean NOT NULL DEFAULT false,
            session_version integer NOT NULL DEFAULT 1,
            session_epoch bigint NOT NULL DEFAULT 1,
            status character varying(50) NOT NULL DEFAULT 'ACTIVE',
            CONSTRAINT user_sessions_pkey PRIMARY KEY (session_id)
        );
        CREATE INDEX idx_user_sessions_refresh ON public.user_sessions(refresh_token);
        CREATE INDEX idx_user_sessions_user ON public.user_sessions(user_id);
    END IF;
END
$$;
