-- Migration: V57__create_training_assignment_scopes_table.sql
-- Purpose: Add training assignment scopes table for Scope vs Execution separation and unique constraints

CREATE TABLE IF NOT EXISTS training_assignment_scopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    training_id BIGINT NOT NULL REFERENCES trainings(id) ON DELETE CASCADE,
    assignment_type VARCHAR(50) NOT NULL, -- DEPARTMENT, TEAM, EMPLOYEE
    target_id VARCHAR(255) NOT NULL,
    mandatory BOOLEAN NOT NULL DEFAULT TRUE,
    due_date DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, REMOVED
    created_by BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_training_scope UNIQUE (training_id, assignment_type, target_id)
);

-- Index for fast lookup by organization and training
CREATE INDEX IF NOT EXISTS idx_trn_scope_org_trn ON training_assignment_scopes(organization_id, training_id);
CREATE INDEX IF NOT EXISTS idx_trn_scope_target ON training_assignment_scopes(assignment_type, target_id);

-- Ensure UNIQUE constraint on training_participants for training_id and employee_id
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_training_employee'
    ) THEN
        ALTER TABLE training_participants ADD CONSTRAINT uk_training_employee UNIQUE (training_id, employee_id);
    END IF;
END $$;
