-- V62__create_goal_management_module.sql
-- Goal Management Module Schema Definition with Multi-Tenant Indexes

-- 1. Main Goals Table (Supports upgrade from legacy V1 goals table)
CREATE TABLE IF NOT EXISTS goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    goal_number VARCHAR(50),
    goal_name VARCHAR(255),
    description TEXT,
    category VARCHAR(100),
    type VARCHAR(100),
    priority VARCHAR(50),
    weightage INT DEFAULT 1,
    progress INT DEFAULT 0,
    start_date DATE,
    end_date DATE,
    target_value DOUBLE PRECISION,
    current_value DOUBLE PRECISION DEFAULT 0.0,
    unit_of_measurement VARCHAR(50),
    owner_id BIGINT,
    estimated_hours DOUBLE PRECISION DEFAULT 0.0,
    actual_hours DOUBLE PRECISION DEFAULT 0.0,
    status VARCHAR(50) DEFAULT 'DRAFT',
    visibility VARCHAR(50) DEFAULT 'PUBLIC',
    parent_goal_id BIGINT,
    project_id BIGINT,
    created_by BIGINT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    version BIGINT DEFAULT 0
);

ALTER TABLE goals ADD COLUMN IF NOT EXISTS organization_id BIGINT DEFAULT 1;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS goal_number VARCHAR(50);
ALTER TABLE goals ADD COLUMN IF NOT EXISTS goal_name VARCHAR(255);
ALTER TABLE goals ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE goals ADD COLUMN IF NOT EXISTS type VARCHAR(100);
ALTER TABLE goals ADD COLUMN IF NOT EXISTS target_value DOUBLE PRECISION;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS current_value DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS unit_of_measurement VARCHAR(50);
ALTER TABLE goals ADD COLUMN IF NOT EXISTS owner_id BIGINT;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS estimated_hours DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS actual_hours DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS visibility VARCHAR(50) DEFAULT 'PUBLIC';
ALTER TABLE goals ADD COLUMN IF NOT EXISTS parent_goal_id BIGINT;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS project_id BIGINT;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

ALTER TABLE goals ALTER COLUMN goal_code DROP NOT NULL;
ALTER TABLE goals ALTER COLUMN title DROP NOT NULL;
ALTER TABLE goals ALTER COLUMN employee_id DROP NOT NULL;



UPDATE goals SET organization_id = 1 WHERE organization_id IS NULL;
UPDATE goals SET goal_number = 'GOAL-' || id WHERE goal_number IS NULL;
UPDATE goals SET goal_name = 'Goal ' || id WHERE goal_name IS NULL;

CREATE INDEX IF NOT EXISTS idx_goals_org_id ON goals(organization_id);
CREATE INDEX IF NOT EXISTS idx_goals_org_owner ON goals(organization_id, owner_id);
CREATE INDEX IF NOT EXISTS idx_goals_org_status ON goals(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_goals_org_parent ON goals(organization_id, parent_goal_id);
CREATE INDEX IF NOT EXISTS idx_goals_org_project ON goals(organization_id, project_id);

-- 2. Goal Assignments
CREATE TABLE IF NOT EXISTS goal_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
    assigned_to_employee_id BIGINT,
    department_id BIGINT,
    team_id BIGINT,
    branch_id BIGINT,
    role_id BIGINT,
    assignment_level VARCHAR(50) NOT NULL,
    assignment_type VARCHAR(50) NOT NULL,
    assigned_by BIGINT,
    assigned_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_goal_assign_org_goal ON goal_assignments(organization_id, goal_id);
CREATE INDEX IF NOT EXISTS idx_goal_assign_org_emp ON goal_assignments(organization_id, assigned_to_employee_id);
CREATE INDEX IF NOT EXISTS idx_goal_assign_org_dept ON goal_assignments(organization_id, department_id);
CREATE INDEX IF NOT EXISTS idx_goal_assign_org_team ON goal_assignments(organization_id, team_id);

-- 3. Goal Assignment History
CREATE TABLE IF NOT EXISTS goal_assignment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL,
    assignment_id BIGINT,
    assigned_to BIGINT,
    assigned_by BIGINT,
    previous_owner_id BIGINT,
    department_id BIGINT,
    team_id BIGINT,
    role_id BIGINT,
    assignment_level VARCHAR(50),
    assignment_type VARCHAR(50),
    assignment_reason TEXT,
    assigned_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    unassigned_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_goal_assign_hist_org_goal ON goal_assignment_history(organization_id, goal_id);

-- 4. Append-Only Goal Progress History
CREATE TABLE IF NOT EXISTS goal_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
    percentage INT NOT NULL,
    target_achieved DOUBLE PRECISION,
    milestone_completed INT,
    tasks_completed INT,
    update_comment TEXT,
    evidence_document VARCHAR(255),
    updated_by BIGINT,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_goal_progress_org_goal ON goal_progress(organization_id, goal_id);

-- 5. Goal Milestones
CREATE TABLE IF NOT EXISTS goal_milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    target_date DATE,
    weightage INT DEFAULT 1,
    status VARCHAR(50) DEFAULT 'PENDING',
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    completed_by BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_goal_milestone_org_goal ON goal_milestones(organization_id, goal_id);

-- 6. Goal Effort Entries
CREATE TABLE IF NOT EXISTS goal_effort_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    hours DOUBLE PRECISION NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_goal_effort_org_goal ON goal_effort_entries(organization_id, goal_id);
CREATE INDEX IF NOT EXISTS idx_goal_effort_org_emp ON goal_effort_entries(organization_id, employee_id);

-- 7. Goal Comments
CREATE TABLE IF NOT EXISTS goal_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    goal_id BIGINT NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
    parent_comment_id BIGINT,
    comment TEXT NOT NULL,
    created_by BIGINT NOT NULL DEFAULT 1,
    is_edited BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE goal_comments ADD COLUMN IF NOT EXISTS organization_id BIGINT DEFAULT 1;
ALTER TABLE goal_comments ADD COLUMN IF NOT EXISTS parent_comment_id BIGINT;
ALTER TABLE goal_comments ADD COLUMN IF NOT EXISTS created_by BIGINT DEFAULT 1;
ALTER TABLE goal_comments ADD COLUMN IF NOT EXISTS is_edited BOOLEAN DEFAULT FALSE;
ALTER TABLE goal_comments ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE goal_comments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;

UPDATE goal_comments SET organization_id = 1 WHERE organization_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_goal_comment_org_goal ON goal_comments(organization_id, goal_id);

-- 8. Goal Attachments
CREATE TABLE IF NOT EXISTS goal_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
    progress_id BIGINT,
    comment_id BIGINT,
    milestone_id BIGINT,
    file_reference VARCHAR(500) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100),
    uploaded_by BIGINT NOT NULL,
    uploaded_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_goal_attach_org_goal ON goal_attachments(organization_id, goal_id);

-- 9. Immutable Goal Activities Timeline Audit Log
CREATE TABLE IF NOT EXISTS goal_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
    actor_employee_id BIGINT,
    actor_name VARCHAR(255),
    actor_role VARCHAR(100),
    action VARCHAR(100) NOT NULL,
    description TEXT,
    metadata TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_goal_activity_org_goal ON goal_activities(organization_id, goal_id);

-- 10. Normalized Configuration Tables
CREATE TABLE IF NOT EXISTS goal_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL UNIQUE,
    min_weightage INT DEFAULT 1,
    max_weightage INT DEFAULT 100,
    allow_milestone_progress_calc BOOLEAN DEFAULT TRUE,
    allow_auto_reassignment BOOLEAN DEFAULT TRUE,
    require_approval_for_create BOOLEAN DEFAULT FALSE,
    require_approval_for_complete BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_goal_configs_org ON goal_configs(organization_id);

CREATE TABLE IF NOT EXISTS goal_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_goal_category_org_code UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS goal_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_goal_type_org_code UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS goal_priorities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_goal_priority_org_code UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS goal_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_system BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_goal_status_org_code UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS goal_assignment_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    rule_name VARCHAR(100) NOT NULL,
    target_level VARCHAR(50) NOT NULL,
    auto_reassign_on_transfer BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS goal_notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    email_enabled BOOLEAN DEFAULT TRUE,
    in_app_enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_goal_notif_org_event UNIQUE (organization_id, event_type)
);

CREATE TABLE IF NOT EXISTS goal_number_formats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL UNIQUE,
    prefix VARCHAR(20) DEFAULT 'GOAL',
    sequence_length INT DEFAULT 5,
    current_sequence BIGINT DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS goal_visibility_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    visibility_code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_goal_visibility_org_code UNIQUE (organization_id, visibility_code)
);

-- 11. Goal Approval Policies Table
CREATE TABLE IF NOT EXISTS goal_approval_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    policy_name VARCHAR(150) NOT NULL,
    module VARCHAR(50) DEFAULT 'GOAL',
    action VARCHAR(50) NOT NULL,
    approval_required BOOLEAN DEFAULT TRUE,
    approval_type VARCHAR(50) DEFAULT 'MANAGER',
    priority VARCHAR(50),
    goal_type VARCHAR(50),
    weightage_threshold INT DEFAULT 0,
    estimated_hours_threshold DOUBLE PRECISION DEFAULT 0.0,
    department_id BIGINT,
    approver_role VARCHAR(50),
    approval_levels INT DEFAULT 1,
    auto_approval BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_goal_approval_policies_org ON goal_approval_policies(organization_id, is_active);
