-- Migration for Recruitment Module Enhancement
DROP TABLE IF EXISTS public.background_verifications CASCADE;
DROP TABLE IF EXISTS public.offers CASCADE;
DROP TABLE IF EXISTS public.interviews CASCADE;
DROP TABLE IF EXISTS public.talent_pool_invitations CASCADE;
DROP TABLE IF EXISTS public.application_status_history CASCADE;
DROP TABLE IF EXISTS public.applications CASCADE;
DROP TABLE IF EXISTS public.candidates CASCADE;
DROP TABLE IF EXISTS public.jobs CASCADE;

-- Jobs Table
CREATE TABLE public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    department_id BIGINT,
    department VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE,
    location VARCHAR(255),
    employment_type VARCHAR(50) NOT NULL DEFAULT 'FULL_TIME',
    experience_min INT NOT NULL DEFAULT 0,
    experience_max INT NOT NULL DEFAULT 0,
    openings INT NOT NULL DEFAULT 1,
    salary_min NUMERIC(15,2),
    salary_max NUMERIC(15,2),
    salary_range VARCHAR(255),
    description TEXT,
    requirements TEXT,
    application_deadline DATE,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_jobs_org_status ON public.jobs(organization_id, status);
CREATE INDEX idx_jobs_slug ON public.jobs(slug);

-- Candidates Table
CREATE TABLE public.candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    experience_years DOUBLE PRECISION NOT NULL DEFAULT 0,
    current_company VARCHAR(255),
    current_designation VARCHAR(255),
    expected_salary NUMERIC(15,2),
    notice_period_days INT,
    cover_letter TEXT,
    resume_url VARCHAR(500),
    resume_file_name VARCHAR(255),
    resume_file_type VARCHAR(100),
    resume_data BYTEA,
    talent_pool_status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE',
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_candidates_org_email UNIQUE (organization_id, email)
);

CREATE INDEX idx_candidates_org_email ON public.candidates(organization_id, email);
CREATE INDEX idx_candidates_org_phone ON public.candidates(organization_id, phone);

-- Applications Table
CREATE TABLE public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_number VARCHAR(100) UNIQUE NOT NULL,
    organization_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL DEFAULT 'APPLIED',
    rejection_reason TEXT,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_application_candidate_job UNIQUE (organization_id, candidate_id, job_id)
);

CREATE INDEX idx_applications_org_job ON public.applications(organization_id, job_id);
CREATE INDEX idx_applications_org_status ON public.applications(organization_id, status);

-- Application Status History Table
CREATE TABLE public.application_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES public.applications(id) ON DELETE CASCADE,
    old_status VARCHAR(50),
    new_status VARCHAR(50) NOT NULL,
    changed_by VARCHAR(255),
    reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_status_history_application ON public.application_status_history(application_id);

-- Interviews Table
CREATE TABLE public.interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL REFERENCES public.applications(id) ON DELETE CASCADE,
    interviewer_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    interviewer_name VARCHAR(255),
    interview_type VARCHAR(50) NOT NULL DEFAULT 'TECHNICAL',
    scheduled_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    meeting_link VARCHAR(500),
    status VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED',
    technical_rating INT,
    communication_rating INT,
    overall_rating INT,
    recommendation VARCHAR(50),
    comments TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_interviews_org_app ON public.interviews(organization_id, application_id);
CREATE INDEX idx_interviews_interviewer_date ON public.interviews(interviewer_id, scheduled_date);

-- Offers Table
CREATE TABLE public.offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL REFERENCES public.applications(id) ON DELETE CASCADE,
    offer_number VARCHAR(100) UNIQUE NOT NULL,
    designation VARCHAR(255) NOT NULL,
    annual_salary NUMERIC(15,2) NOT NULL,
    joining_date DATE NOT NULL,
    probation_months INT NOT NULL DEFAULT 6,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    acceptance_token VARCHAR(255) UNIQUE,
    sent_at TIMESTAMP,
    accepted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_offers_org_app ON public.offers(organization_id, application_id);
CREATE INDEX idx_offers_token ON public.offers(acceptance_token);

-- Talent Pool Invitations Table
CREATE TABLE public.talent_pool_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
    invited_by VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'INVITED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Background Verifications Table
CREATE TABLE public.background_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    verification_agency VARCHAR(255),
    reports_metadata TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

