-- Migration to create Exit Knowledge Transfer Plan (KTP) and Manager Recommendation tables

CREATE TABLE public.exit_kt_plan (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_id bigint NOT NULL,
    handover_person_id bigint,
    status character varying(30) DEFAULT 'IN_PROGRESS'::character varying,
    projects_completed boolean NOT NULL DEFAULT false,
    contacts_completed boolean NOT NULL DEFAULT false,
    system_credentials_completed boolean NOT NULL DEFAULT false,
    pending_tasks_completed boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT exit_kt_plan_pkey PRIMARY KEY (id),
    CONSTRAINT exit_kt_plan_employee_id_key UNIQUE (employee_id),
    CONSTRAINT fk_exit_kt_plan_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_exit_kt_plan_handover FOREIGN KEY (handover_person_id) REFERENCES public.employees(id) ON DELETE SET NULL
);

CREATE TABLE public.exit_kt_projects (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    kt_plan_id bigint NOT NULL,
    project_name character varying(255) NOT NULL,
    status character varying(30) DEFAULT 'IN_PROGRESS'::character varying,
    handover_notes text,
    risk_level character varying(20) DEFAULT 'MEDIUM'::character varying,
    CONSTRAINT exit_kt_projects_pkey PRIMARY KEY (id),
    CONSTRAINT fk_exit_kt_projects_plan FOREIGN KEY (kt_plan_id) REFERENCES public.exit_kt_plan(id) ON DELETE CASCADE
);

CREATE TABLE public.exit_kt_contacts (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    kt_plan_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    role character varying(255),
    email character varying(255),
    responsibility text,
    CONSTRAINT exit_kt_contacts_pkey PRIMARY KEY (id),
    CONSTRAINT fk_exit_kt_contacts_plan FOREIGN KEY (kt_plan_id) REFERENCES public.exit_kt_plan(id) ON DELETE CASCADE
);

CREATE TABLE public.exit_kt_system_access (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    kt_plan_id bigint NOT NULL,
    system_name character varying(255) NOT NULL,
    access_type character varying(50),
    status character varying(30) DEFAULT 'ACTIVE'::character varying, -- ACTIVE / REVOKED
    handover_status character varying(30) DEFAULT 'PENDING'::character varying, -- PENDING / TRANSFERRED
    CONSTRAINT exit_kt_system_access_pkey PRIMARY KEY (id),
    CONSTRAINT fk_exit_kt_system_access_plan FOREIGN KEY (kt_plan_id) REFERENCES public.exit_kt_plan(id) ON DELETE CASCADE
);

CREATE TABLE public.exit_kt_tasks (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    kt_plan_id bigint NOT NULL,
    task_name character varying(255) NOT NULL,
    status character varying(30) DEFAULT 'PENDING'::character varying,
    due_date date,
    completed_at timestamp without time zone,
    CONSTRAINT exit_kt_tasks_pkey PRIMARY KEY (id),
    CONSTRAINT fk_exit_kt_tasks_plan FOREIGN KEY (kt_plan_id) REFERENCES public.exit_kt_plan(id) ON DELETE CASCADE
);

CREATE TABLE public.exit_recommendations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_id bigint NOT NULL,
    rating double precision,
    recommendation text,
    created_by bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    locked boolean DEFAULT false,
    CONSTRAINT exit_recommendations_pkey PRIMARY KEY (id),
    CONSTRAINT exit_recommendations_employee_id_key UNIQUE (employee_id),
    CONSTRAINT fk_exit_recommendations_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_exit_recommendations_created_by FOREIGN KEY (created_by) REFERENCES public.employees(id) ON DELETE SET NULL
);
