-- Migration V91: Create Offboarding Template Framework Tables

CREATE TABLE IF NOT EXISTS public.offboarding_templates (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    status character varying(50) DEFAULT 'ACTIVE' NOT NULL,
    department_ids_json text,
    employment_types_json text,
    employee_types_json text,
    notice_period_enabled boolean DEFAULT true,
    notice_period_default_days integer DEFAULT 30,
    allow_early_release boolean DEFAULT true,
    allow_notice_period_buyout boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT offboarding_templates_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_offboarding_templates_org_status ON public.offboarding_templates (organization_id, status);

CREATE TABLE IF NOT EXISTS public.offboarding_clearance_task_templates (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    template_id bigint NOT NULL,
    task_name character varying(255) NOT NULL,
    description text,
    assign_to_type character varying(50) NOT NULL,
    assigned_user_id bigint,
    due_before_lwd_days integer DEFAULT 3,
    priority character varying(50) DEFAULT 'MEDIUM',
    mandatory boolean DEFAULT true,
    approval_required boolean DEFAULT false,
    sequence integer DEFAULT 1,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT offboarding_clearance_task_templates_pkey PRIMARY KEY (id),
    CONSTRAINT fk_offboarding_clearance_task_template FOREIGN KEY (template_id) REFERENCES public.offboarding_templates(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_offboarding_clearance_tasks_org_tpl ON public.offboarding_clearance_task_templates (organization_id, template_id);

CREATE TABLE IF NOT EXISTS public.offboarding_asset_requirement_templates (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    template_id bigint NOT NULL,
    asset_type character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    return_required boolean DEFAULT true,
    condition_check_required boolean DEFAULT true,
    serial_number_verification_required boolean DEFAULT true,
    due_before_lwd_days integer DEFAULT 1,
    assigned_to_type character varying(50) NOT NULL,
    assigned_user_id bigint,
    mandatory boolean DEFAULT true,
    approval_required boolean DEFAULT false,
    sequence integer DEFAULT 1,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT offboarding_asset_requirement_templates_pkey PRIMARY KEY (id),
    CONSTRAINT fk_offboarding_asset_requirement_template FOREIGN KEY (template_id) REFERENCES public.offboarding_templates(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_offboarding_asset_reqs_org_tpl ON public.offboarding_asset_requirement_templates (organization_id, template_id);

CREATE TABLE IF NOT EXISTS public.offboarding_document_requirement_templates (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    template_id bigint NOT NULL,
    document_type character varying(50) NOT NULL,
    document_name character varying(255) NOT NULL,
    description text,
    required boolean DEFAULT true,
    action character varying(50) DEFAULT 'GENERATE' NOT NULL,
    owner_type character varying(50) NOT NULL,
    owner_user_id bigint,
    due_before_lwd_days integer DEFAULT 0,
    employee_upload_required boolean DEFAULT false,
    approval_required boolean DEFAULT false,
    sequence integer DEFAULT 1,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT offboarding_document_requirement_templates_pkey PRIMARY KEY (id),
    CONSTRAINT fk_offboarding_document_requirement_template FOREIGN KEY (template_id) REFERENCES public.offboarding_templates(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_offboarding_doc_reqs_org_tpl ON public.offboarding_document_requirement_templates (organization_id, template_id);

CREATE TABLE IF NOT EXISTS public.offboarding_kt_templates (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    template_id bigint NOT NULL,
    required boolean DEFAULT true,
    title character varying(255) NOT NULL,
    description text,
    assign_to_type character varying(50) NOT NULL,
    assigned_user_id bigint,
    employee_responsibilities_json text,
    handover_document_required boolean DEFAULT true,
    handover_approval_required boolean DEFAULT true,
    due_before_lwd_days integer DEFAULT 5,
    priority character varying(50) DEFAULT 'HIGH',
    mandatory boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT offboarding_kt_templates_pkey PRIMARY KEY (id),
    CONSTRAINT uq_offboarding_kt_template_template_id UNIQUE (template_id),
    CONSTRAINT fk_offboarding_kt_template_template FOREIGN KEY (template_id) REFERENCES public.offboarding_templates(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_offboarding_kt_templates_org ON public.offboarding_kt_templates (organization_id, template_id);

CREATE TABLE IF NOT EXISTS public.offboarding_interview_templates (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    template_id bigint NOT NULL,
    enabled boolean DEFAULT true,
    conducted_by_type character varying(50) NOT NULL,
    conducted_by_user_id bigint,
    mandatory boolean DEFAULT true,
    due_before_lwd_days integer DEFAULT 2,
    allow_anonymous_feedback boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT offboarding_interview_templates_pkey PRIMARY KEY (id),
    CONSTRAINT uq_offboarding_interview_template_template_id UNIQUE (template_id),
    CONSTRAINT fk_offboarding_interview_template_template FOREIGN KEY (template_id) REFERENCES public.offboarding_templates(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_offboarding_interview_templates_org ON public.offboarding_interview_templates (organization_id, template_id);

CREATE TABLE IF NOT EXISTS public.offboarding_interview_questions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    interview_template_id bigint NOT NULL,
    question text NOT NULL,
    question_type character varying(50) NOT NULL,
    required boolean DEFAULT true,
    options_json text,
    min_value integer,
    max_value integer,
    sequence integer DEFAULT 1,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT offboarding_interview_questions_pkey PRIMARY KEY (id),
    CONSTRAINT fk_offboarding_interview_question_template FOREIGN KEY (interview_template_id) REFERENCES public.offboarding_interview_templates(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_offboarding_interview_questions_org ON public.offboarding_interview_questions (organization_id, interview_template_id);
