-- Migration V92: Create Offboarding Employee Template Assignments Table

CREATE TABLE IF NOT EXISTS public.offboarding_employee_template_assignments (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    template_id bigint NOT NULL,
    exit_type character varying(50) DEFAULT 'ALL' NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT offboarding_employee_template_assignments_pkey PRIMARY KEY (id),
    CONSTRAINT fk_offboarding_emp_tpl_assign_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_offboarding_emp_tpl_assign_template FOREIGN KEY (template_id) REFERENCES public.offboarding_templates(id) ON DELETE CASCADE,
    CONSTRAINT uq_offboarding_emp_tpl_assign UNIQUE (organization_id, employee_id, exit_type)
);

CREATE INDEX IF NOT EXISTS idx_offboarding_emp_tpl_org_emp ON public.offboarding_employee_template_assignments (organization_id, employee_id);
CREATE INDEX IF NOT EXISTS idx_offboarding_emp_tpl_org_tpl ON public.offboarding_employee_template_assignments (organization_id, template_id);
