package com.example.ems.approval.entity;

public enum WorkflowType {
    SCHEDULE_SWAP,
    SCHEDULE_RESCHEDULE,
    ONBOARDING_APPROVAL,
    LEAVE_APPROVAL,
    EXPENSE_APPROVAL,
    TRAINING_APPROVAL,
    ASSET_ASSIGNMENT_APPROVAL,
    ASSET_TRANSFER_APPROVAL,
    ASSET_RETIREMENT_APPROVAL,
    ASSET_DISPOSAL_APPROVAL,
    ASSET_MAINTENANCE_APPROVAL,
    GOAL_APPROVAL,
    GOAL_CREATION_APPROVAL,
    GOAL_COMPLETION_APPROVAL
}

